First section: transforming the data (in csv) into a table-form in Pandas.

Fixed-Income and Credit Derivatives

Second Assignment

Student: István Baksa

In [2]:
import pandas as pd             # Importing Pandas
from io import StringIO

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

# Creating a text object that will be turned into a virtual csv file in the next step. I copied the csv data here so that it has not to be imported from an external source.

data_text = '''Firm;"Initial state 1";"Time in state 1";"New state 1";"Time in new state 1";"New state 2";"Time in new state 2"
#1;A;1;B*;3;B;20
#2;A;2;B*;14;B;8
#3;A;4;B*;8;B;12
#4;A;9;B*;4;D;11
#5;A;11;B*;13;0;0
#6;A;14;B*;6;A;4
#7;A;14;B*;9;D;1
#8;A;19;B*;3;B;2
#9;A;21;B*;3;0;0
#10;A;23;B*;1;0;0
#11;A;24;0;0;0;0
#12;A;24;0;0;0;0
#13;A;24;0;0;0;0
#14;A;24;0;0;0;0
#15;A;24;0;0;0;0
#16;A;24;0;0;0;0
#17;A;24;0;0;0;0
#18;A;24;0;0;0;0
#19;A;24;0;0;0;0
#20;A;24;0;0;0;0
#21;A;24;0;0;0;0
#22;A;24;0;0;0;0
#23;A;24;0;0;0;0
#24;A;24;0;0;0;0
#25;A;24;0;0;0;0
#26;A;24;0;0;0;0
#27;A;24;0;0;0;0
#28;A;24;0;0;0;0
#29;A;24;0;0;0;0
#30;A;24;0;0;0;0
#31;A;24;0;0;0;0
#32;A;24;0;0;0;0
#33;A;24;0;0;0;0
#34;A;24;0;0;0;0
#35;A;24;0;0;0;0
#36;A;24;0;0;0;0
#37;A;24;0;0;0;0
#38;A;24;0;0;0;0
#39;A;24;0;0;0;0
#40;A;24;0;0;0;0
#41;A;24;0;0;0;0
#42;A;24;0;0;0;0
#43;A;24;0;0;0;0
#44;A;24;0;0;0;0
#45;A;24;0;0;0;0
#46;A;24;0;0;0;0
#47;A;24;0;0;0;0
#48;A;24;0;0;0;0
#49;A;24;0;0;0;0
#50;A;24;0;0;0;0
#51;A;24;0;0;0;0
#52;A;24;0;0;0;0
#53;A;24;0;0;0;0
#54;A;24;0;0;0;0
#55;A;24;0;0;0;0
#56;A;24;0;0;0;0
#57;A;24;0;0;0;0
#58;A;24;0;0;0;0
#59;A;24;0;0;0;0
#60;A;24;0;0;0;0
#61;A;24;0;0;0;0
#62;A;24;0;0;0;0
#63;A;24;0;0;0;0
#64;A;24;0;0;0;0
#65;A;24;0;0;0;0
#66;A;24;0;0;0;0
#67;A;24;0;0;0;0
#68;A;24;0;0;0;0
#69;A;24;0;0;0;0
#70;A;24;0;0;0;0
#71;A;24;0;0;0;0
#72;A;24;0;0;0;0
#73;A;24;0;0;0;0
#74;A;24;0;0;0;0
#75;A;24;0;0;0;0
#76;A;24;0;0;0;0
#77;A;24;0;0;0;0
#78;A;24;0;0;0;0
#79;A;24;0;0;0;0
#80;A;24;0;0;0;0
#81;A;24;0;0;0;0
#82;A;24;0;0;0;0
#83;A;24;0;0;0;0
#84;A;24;0;0;0;0
#85;A;24;0;0;0;0
#86;A;24;0;0;0;0
#87;A;24;0;0;0;0
#88;A;24;0;0;0;0
#89;A;24;0;0;0;0
#90;A;24;0;0;0;0
#91;A;24;0;0;0;0
#92;A;24;0;0;0;0
#93;A;24;0;0;0;0
#94;A;24;0;0;0;0
#95;A;24;0;0;0;0
#96;A;24;0;0;0;0
#97;A;24;0;0;0;0
#98;A;24;0;0;0;0
#99;A;24;0;0;0;0
#100;A;24;0;0;0;0
#101;B;1;A;23;0;0
#102;B;3;A;18;B*;3
#103;B;7;A;17;0;0
#104;B;12;A;9;B*;3
#105;B;15;A;5;B*;4
#106;B;18;A;6;0;0
#107;B;18;A;4;B*;2
#108;B;20;A;4;0;0
#109;B;21;A;3;0;0
#110;B;23;A;1;0;0
#111;B;2;D;22;0;0
#112;B;8;D;16;0;0
#113;B;18;D;6;0;0
#114;B;19;D;5;0;0
#115;B;22;D;2;0;0
#116;B;24;0;0;0;0
#117;B;24;0;0;0;0
#118;B;24;0;0;0;0
#119;B;24;0;0;0;0
#120;B;24;0;0;0;0
#121;B;24;0;0;0;0
#122;B;24;0;0;0;0
#123;B;24;0;0;0;0
#124;B;24;0;0;0;0
#125;B;24;0;0;0;0
#126;B;24;0;0;0;0
#127;B;24;0;0;0;0
#128;B;24;0;0;0;0
#129;B;24;0;0;0;0
#130;B;24;0;0;0;0
#131;B;24;0;0;0;0
#132;B;24;0;0;0;0
#133;B;24;0;0;0;0
#134;B;24;0;0;0;0
#135;B;24;0;0;0;0
#136;B;24;0;0;0;0
#137;B;24;0;0;0;0
#138;B;24;0;0;0;0
#139;B;24;0;0;0;0
#140;B;24;0;0;0;0
#141;B;24;0;0;0;0
#142;B;24;0;0;0;0
#143;B;24;0;0;0;0
#144;B;24;0;0;0;0
#145;B;24;0;0;0;0
#146;B;24;0;0;0;0
#147;B;24;0;0;0;0
#148;B;24;0;0;0;0
#149;B;24;0;0;0;0
#150;B;24;0;0;0;0
#151;B;24;0;0;0;0
#152;B;24;0;0;0;0
#153;B;24;0;0;0;0
#154;B;24;0;0;0;0
#155;B;24;0;0;0;0
#156;B;24;0;0;0;0
#157;B;24;0;0;0;0
#158;B;24;0;0;0;0
#159;B;24;0;0;0;0
#160;B;24;0;0;0;0
#161;B;24;0;0;0;0
#162;B;24;0;0;0;0
#163;B;24;0;0;0;0
#164;B;24;0;0;0;0
#165;B;24;0;0;0;0
#166;B;24;0;0;0;0
#167;B;24;0;0;0;0
#168;B;24;0;0;0;0
#169;B;24;0;0;0;0
#170;B;24;0;0;0;0
#171;B;24;0;0;0;0
#172;B;24;0;0;0;0
#173;B;24;0;0;0;0
#174;B;24;0;0;0;0
#175;B;24;0;0;0;0
#176;B;24;0;0;0;0
#177;B;24;0;0;0;0
#178;B;24;0;0;0;0
#179;B;24;0;0;0;0
#180;B;24;0;0;0;0
#181;B;24;0;0;0;0
#182;B;24;0;0;0;0
#183;B;24;0;0;0;0
#184;B;24;0;0;0;0
#185;B;24;0;0;0;0
#186;B;24;0;0;0;0
#187;B;24;0;0;0;0
#188;B;24;0;0;0;0
#189;B;24;0;0;0;0
#190;B;24;0;0;0;0
#191;B;24;0;0;0;0
#192;B;24;0;0;0;0
#193;B;24;0;0;0;0
#194;B;24;0;0;0;0
#195;B;24;0;0;0;0
#196;B;24;0;0;0;0
#197;B;24;0;0;0;0
#198;B;24;0;0;0;0
#199;B;24;0;0;0;0
#200;B;24;0;0;0;0'''

data_io = StringIO(data_text)         # Turning the text object into a virtual csv file

df = pd.read_csv(data_io, sep=';')    # Reading the virtual csv file in

df = df.replace('B*','*')     # Changing B* to *, otherwise it will mess up the lists in the next section, as it consists of two characters instead of one.

display(df.head())     # Displaying table

Firm Initial state 1  Time in state 1 New state 1  Time in new state 1  \
0   #1               A                1           *                    3   
1   #2               A                2           *                   14   
2   #3               A                4           *                    8   
3   #4               A                9           *                    4   
4   #5               A               11           *                   13   

  New state 2  Time in new state 2  
0           B                   20  
1           B                    8  
2           B                   12  
3           D                   11  
4           0                    0

Next Section: Calculating total number of years in each of the possible states (A, B*, B, D)

In [3]:
timetotalA = 0              # Initializing variables that will store the total number of years spent in a given state
timetotalStar = 0
timetotalB = 0
timetotalD = 0

for i in range(200):
  for j in range(3):
    if df.iloc[i,(2*j + 1)] == 'A':
     timetotalA = timetotalA + (df.iloc[i,(2*j + 2)] / 12)
    elif df.iloc[i,(2*j + 1)] == '*':
     timetotalStar = timetotalStar + (df.iloc[i,(2*j + 2)] / 12)
    elif df.iloc[i,(2*j + 1)] == 'B':
     timetotalB = timetotalB + (df.iloc[i,(2*j + 2)] / 12)
    elif df.iloc[i,(2*j + 1)] == 'D':
     timetotalD = timetotalD + (df.iloc[i,(2*j + 2)] / 12)

The next section creates a list of 24 characters for each of the firms. Each character represesents a month of rating. For example, A***BBBBBBBBBBBBBBBBBBBB means that the firm spent the first month of the observed 24-month period in state A, then three months in B* and the rest in B.

In [ ]:
list_1 = []                        # Creating an empty list which will serve as a list of lists

for i in range(0, 200):

  list_2 = df.iloc[i,1] * df.iloc[i,2] + df.iloc[i,3] * df.iloc[i,4] + df.iloc[i,5] * df.iloc[i,6]     # Creating a list with the ratings of the firm number i
  list_1.append(list_2)            # Appending the list of lists. Each element on the list is a list with the ratings of a firm.

In [ ]:
list_3 = []                                 # Creating an empty list

for i in range(0,200):                      # Fist for loop with 200 iterations for the 200 firms
 s1 = str(list_1[i][0]) + str(list_1[i][11])      # Creating a pair of rating classifications that are in 12 months distance
 s2 = str(list_1[i][12]) + str(list_1[i][23])
 list_3.append(s1)
 list_3.append(s2)

In [6]:
AA = 0
Astar = 0
AB = 0
AD = 0
starA = 0
starstar = 0
starB = 0
starD = 0
BA = 0
Bstar = 0
BB = 0
BD = 0
DD = 0

for i in range(len(list_3)):
  if list_3[i] == 'AA':
    AA = AA + 1
  elif  list_3[i] == 'A*':
    Astar = Astar + 1
  elif  list_3[i] == 'AB':
    AB = AB + 1
  elif  list_3[i] == 'AD':
    AD = AD + 1
  elif  list_3[i] == '*A':
    starA = starA + 1
  elif  list_3[i] == '**':
    starstar = starstar + 1
  elif  list_3[i] == '*B':
    starB = starB + 1
  elif  list_3[i] == '*D':
    starD = starD + 1
  elif  list_3[i] == 'BA':
    BA = BA + 1
  elif  list_3[i] == 'B*':
    Bstar = Bstar + 1
  elif  list_3[i] == 'BB':
    BB = BB + 1
  elif  list_3[i] == 'BD':
    BD = BD + 1
  elif  list_3[i] == 'DD':
    DD = DD + 1
print(AA+Astar+AB+AD+starA+starstar+starB+starD+BA+Bstar+BB+BD+DD)  # This is a quick check whether all possibilities pairs are counted. The result should be 400.

400


In [7]:
import numpy as np
from scipy.linalg import logm, expm

total_A = AA + Astar + AB + AD
total_star = starA + starstar + starB + starD
total_B = BA + Bstar + BB + BD
total_D = DD

df1 = pd.DataFrame(index=["Initial State: A", "Initial State: B*", "Initial State: B", "Initial State: D"], columns=["A", "B*", "B", "D"])

df1.iloc[0,0] = AA
df1.iloc[0,1] = Astar
df1.iloc[0,2] = AB
df1.iloc[0,3] = AD
df1.iloc[1,0] = starA
df1.iloc[1,1] = starstar
df1.iloc[1,2] = starB
df1.iloc[1,3] = starD
df1.iloc[2,0] = BA
df1.iloc[2,1] = Bstar
df1.iloc[2,2] = BB
df1.iloc[2,3] = BD
df1.iloc[3,0] = 0         # This has to be zero, as D (Default) is an absorbing state, meaning that if a rating gets downgraded to D, it stays there; there is no move from D to A.
df1.iloc[3,1] = 0
df1.iloc[3,2] = 0
df1.iloc[3,3] = DD



df2 = df1.copy()
df3 = df1.copy()

df2.iloc[0]=df2.iloc[0]/total_A
df2.iloc[1]=df2.iloc[1]/total_star
df2.iloc[2]=df2.iloc[2]/total_B
df2.iloc[3]=df2.iloc[3]/total_D

df3.iloc[0]=df3.iloc[0]/timetotalA
df3.iloc[1]=df3.iloc[1]/timetotalStar
df3.iloc[2]=df3.iloc[2]/timetotalB
df3.iloc[3]=df3.iloc[3]/total_D

df3.iloc[0,0] = - (df3.iloc[0,1] + df3.iloc[0,2] + df3.iloc[0,3])
df3.iloc[1,1] = - (df3.iloc[1,0] + df3.iloc[1,2] + df3.iloc[1,3])
df3.iloc[2,2] = - (df3.iloc[2,0] + df3.iloc[2,1] + df3.iloc[2,3])
df3.iloc[3,3] =   (df3.iloc[3,0] + df3.iloc[3,1] + df3.iloc[3,2])

In [8]:
total_A_poorer = AA + Astar + AB + AD
total_B_poorer = BA + Bstar + BB + BD + starA + starstar + starB + starD
total_D_poorer = DD

timetotalA_poorer = timetotalA
timetotalB_poorer = timetotalStar + timetotalB
timetotalD_poorer = 0

AA_poorer = AA
AB_poorer = Astar + AB
AD_poorer = AD

BA_poorer = BA + starA
BB_poorer = starstar + BB + starB + Bstar
BD_poorer = starD + BD

DD_poorer = DD

df4 = pd.DataFrame(index=["Initial State: A", "Initial State: B", "Initial State: D"], columns=["A", "B", "D"])

df4.iloc[0,0] = AA_poorer
df4.iloc[0,1] = AB_poorer
df4.iloc[0,2] = AD_poorer
df4.iloc[1,0] = BA_poorer
df4.iloc[1,1] = BB_poorer
df4.iloc[1,2] = BD_poorer
df4.iloc[2,0] = 0         # This has to be zero, as D (Default) is an absorbing state, meaning that if a rating gets downgraded to D, it stays there; there is no move from D to A.
df4.iloc[2,1] = 0
df4.iloc[2,2] = DD

df5 = df4.copy()
df6 = df4.copy()

df5.iloc[0]=df5.iloc[0]/total_A_poorer
df5.iloc[1]=df5.iloc[1]/total_B_poorer
df5.iloc[2]=df5.iloc[2]/total_D_poorer

df6.iloc[0]=df6.iloc[0]/timetotalA_poorer
df6.iloc[1]=df6.iloc[1]/timetotalB_poorer
df6.iloc[2]=df6.iloc[2]/timetotalB_poorer


df6.iloc[0,0] = - (df6.iloc[0,1] + df6.iloc[0,2])
df6.iloc[1,1] = - (df6.iloc[1,0] + df6.iloc[1,2])
df6.iloc[2,2] =   (df6.iloc[2,0] + df6.iloc[2,1])

1. By using the cohort estimator, compute the (1-year) transition probability
matrices both in the (Markov) case with a richer state space and in the
(non-Markov) case with a poorer state space.

In [9]:
print('\n','Solutions')

print('\n','\n','\n','Matrix of transitions for a one-year period (absolute numbers, richer state space):','\n')
display(df1)

print('\n','\n','\n','Transition probabilities for a one-year period, Cohort method, richer state space:', '\n')
display(df2)

print('\n','\n','\n', 'Matrix of transitions for a one-year period (absolute numbers, poorer state space):','\n')
display(df4)

print('\n','\n','\n','Transition probabilities for a one-year period, Cohort method, poorer state space:', '\n')
display(df5)

d = np.around(df5.to_numpy().astype(float), decimals = 4)         # Converting the table to a matrix
d_log = logm(d)

print('\n','\n','\n', "Cohort method generator matrix, poorer  state space:", '\n')
print(d_log)


 Solutions

 
 
 Matrix of transitions for a one-year period (absolute numbers, richer state space): 



A B*    B  D
Initial State: A   188  8    2  1
Initial State: B*    0  1    1  1
Initial State: B     7  2  182  5
Initial State: D     0  0    0  2


 
 
 Transition probabilities for a one-year period, Cohort method, richer state space: 



A        B*         B         D
Initial State: A   0.944724  0.040201   0.01005  0.005025
Initial State: B*       0.0  0.333333  0.333333  0.333333
Initial State: B   0.035714  0.010204  0.928571   0.02551
Initial State: D        0.0       0.0       0.0       1.0


 
 
 Matrix of transitions for a one-year period (absolute numbers, poorer state space): 



A    B  D
Initial State: A  188   10  1
Initial State: B    7  186  6
Initial State: D    0    0  2


 
 
 Transition probabilities for a one-year period, Cohort method, poorer state space: 



A         B         D
Initial State: A  0.944724  0.050251  0.005025
Initial State: B  0.035176  0.934673  0.030151
Initial State: D       0.0       0.0       1.0


 
 
 Cohort method generator matrix, poorer  state space: 

[[-0.05788788  0.05356405  0.0043211 ]
 [ 0.03748418 -0.06853679  0.03115609]
 [ 0.          0.          0.        ]]


2. By using the direct ML estimator, compute the (1-year) generator matrices
both in the (Markov) case with a richer state space and in the (non-
Markov) case with a poorer state space.

In [10]:
print('\n','Solutions')

print('\n','\n','\n', "Time-continuous generator matrix richer state space:", '\n')
display(df3)

a = np.around(df3.to_numpy().astype(float), decimals = 4)         # Converting the table to a matrix
a_exp = expm(a)

b = np.around(df2.to_numpy().astype(float), decimals = 4)         # Converting the table to a matrix
b_log = logm(b)


print('\n','\n','\n', "Time-continuous transition matrix, richer state space:", '\n')
print(a_exp)

print('\n','\n','\n', "Time-continuous generator matrix, poorer state space:", '\n')
display(df6)

c = np.around(df6.to_numpy().astype(float), decimals = 4)         # Converting the table to a matrix
c_exp = expm(c)

print('\n','\n','\n', "Time-continuous transition matrix, poorer state space:", '\n')
print(c_exp)


 Solutions

 
 
 Time-continuous generator matrix richer state space: 



A        B*         B         D
Initial State: A  -0.055649  0.040472  0.010118  0.005059
Initial State: B*       0.0 -0.315789  0.157895  0.157895
Initial State: B   0.036697  0.010485 -0.073394  0.026212
Initial State: D        0.0       0.0       0.0       0.0


 
 
 Time-continuous transition matrix, richer state space: 

[[0.94612629 0.03378876 0.01223451 0.00794771]
 [0.00250298 0.72989424 0.13034188 0.13726099]
 [0.0344194  0.00930944 0.93014853 0.02612439]
 [0.         0.         0.         1.        ]]

 
 
 Time-continuous generator matrix, poorer state space: 



A         B         D
Initial State: A -0.055649   0.05059  0.005059
Initial State: B  0.035518 -0.065962  0.030444
Initial State: D       0.0       0.0       0.0


 
 
 Time-continuous transition matrix, poorer state space: 

[[0.94676419 0.04762965 0.00570103]
 [0.03341606 0.9369747  0.02951415]
 [0.         0.         1.        ]]


3. For both state spaces, explain the difference in the 1-year default probabilities between the discrete-time and the continuous-time estimator.

Solution: A great weakness of the cohort method is that it is too dependent on actual, observed past changes in the rating. If historical data does not go back long enough in the past to have rare default events, it can be that the estimated default probability is zero which appears to suggest that the initial state is riskless. This can never happen with the continuous-time method, as it always produces positive transition probabilities.

4. What happens to the 1-year default probability from the "official" states
A and B when there is an additional state? Do the results correspond to
the interpretation of B* as an "excited" state?

Solution:

When there is an additional state, the probability of defaulting from A within a year does not change with the cohort method. This is due to the fact that there was only one actual observation of a firm going from A to D in the course of one year. As for BD of the cohort method, the probability decreases with increasing state space.

Continuous-Time method: If we replace all of the B* states with B, the firms will spend more time in B, so the elements of the generator matrix will decrease which will in turn lead to the decrease of the transition probability.

If one looks at the transition intensities of the generator matrices, it seems to be clear that these are greater than with other states, so B* seems to be an "excited" state.



In [42]:
print("Cohort method", '\n')

print("One-year default probability from A (richer state space): ",df2.iloc[0][3], '\n')
print("One-year default probability from A (poorer state space): ",df5.iloc[0][2], '\n')
print("Difference:", df2.iloc[0][3] - df5.iloc[0][2])

print('\n','\n',"One-year default probability from B (richer state space): ",df2.iloc[2][3], '\n')
print("One-year default probability from B (poorer state space): ",df5.iloc[1][2], '\n')
print("Difference:", df2.iloc[2][3] - df5.iloc[1][2])

print('\n','\n',"Continuous-time-method",'\n')

print("One-year default probability from A (richer state space): ", a_exp[0,3], '\n')
print("One-year default probability from A (poorer state space): ", c_exp[0,2], '\n')
print("Difference: ", a_exp[0,3] - c_exp[0,2])

print('\n','\n',"One-year default probability from B (richer state space): ", a_exp[2,3], '\n')
print("One-year default probability from B (poorer state space): ", c_exp[1,2], '\n')
print("Difference: ", a_exp[2,3] - c_exp[1,2])

Cohort method 

One-year default probability from A (richer state space):  0.005025125628140704 

One-year default probability from A (poorer state space):  0.005025125628140704 

Difference: 0.0

 
 One-year default probability from B (richer state space):  0.025510204081632654 

One-year default probability from B (poorer state space):  0.03015075376884422 

Difference: -0.004640549687211566

 
 Continuous-time-method 

One-year default probability from A (richer state space):  0.007947712243771742 

One-year default probability from A (poorer state space):  0.005701028195382033 

Difference:  0.0022466840483897086

 
 One-year default probability from B (richer state space):  0.026124394284304343 

One-year default probability from B (poorer state space):  0.02951414782685109 

Difference:  -0.003389753542546746
